<a href="https://colab.research.google.com/github/25068645-design/1002/blob/main/%E2%80%9CUntitled%E2%80%9D%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
print("Array 2*2:\n",arr1)

Array 2*2:
 [[1 2]
 [3 4]]


In [ ]:
import numpy as np
arr2=np.random.rand(3,4)
print("\nRandom Arrcy 3*4:\n",arr2)


Random Arrcy 3*4:
 [[0.79776929 0.61924789 0.01788218 0.49548228]
 [0.51826315 0.30451306 0.61141774 0.01760098]
 [0.37066545 0.08593447 0.76001866 0.83315822]]


In [ ]:
import numpy as np
ones =np.ones((2,3))
zeroes =np.zeros((2,3))
print("\nArray of Ones:\n",ones)
print("\nArray of Zeroes:\n",zeroes)


Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Array of Zeroes:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
arr3=np.random.randint(0,10,(6,3))
print("\nRandom 6*3array:\n",arr3)
print("\nTransposed3*6array:\n",arr3.T)



Random 6*3array:
 [[5 3 6]
 [3 5 1]
 [9 1 3]
 [0 5 5]
 [4 9 4]
 [1 7 1]]

Transposed3*6array:
 [[5 3 9 0 4 1]
 [3 5 1 5 9 7]
 [6 1 3 5 4 1]]


In [ ]:
import numpy as np
n,p,m=2,3,4
A=np.random.randint(0,10,(n,p))
B=np.random.randint(0,10,(p,m))
dot_product=np.dot(A,B)
print("\nMatrixA({}*{}:\n".format(n,p),A)
print("\nMatrixB({}*{}:\n".format(p,m),B)
print("\nDot Product ({}*{}):\n".format(n,m),dot_product)



MatrixA(2*3:
 [[0 3 6]
 [8 5 3]]

MatrixB(3*4:
 [[2 4 4 7]
 [1 0 3 0]
 [4 8 9 0]]

Dot Product (2*4):
 [[27 48 63  0]
 [33 56 74 56]]
